### ISSUE TITLE
Ethcapital.net phishing scam

### ISSUE THREAD

**Issue by RobYyyyyy** [pandaoh/js-xhttp#2]
Likely similar to the panda, a Ethereum mining scam that accesses and cleans out your wallet…puzzling how that’s possible if there is any integrity/security/legitimacy of crypto and coinbase/wallet without any contract or authorization. Track em down and make ‘em pay if there ever will be…they leave a messy trail of blockchain, ips and account transfers…why not promptly prosecute?

**Comment by pandaoh** [comment]
Dude, you probably talk it to the wrong repo.

**Comment by RobYyyyyy** [comment]
That was what was linked to the panda scam one, just trying to give a heads up to any others

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
